"""Tests for Aegis SCA — manifest parsers and OSV.dev client (Phase 16)."""
from __future__ import annotations

import asyncio
import json
import textwrap
from pathlib import Path
from unittest.mock import AsyncMock, MagicMock

import pytest

from max_engine.aegis.deps import Package, _parse_python, _parse_npm, _parse_cargo, parse_all
from max_engine.aegis.osv import query_osv, _extract_severity, _extract_fixed_version


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def write(tmp_path: Path, rel: str, content: str) -> Path:
    p = tmp_path / rel
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(textwrap.dedent(content), encoding="utf-8")
    return p


# ---------------------------------------------------------------------------
# Python manifest parser
# ---------------------------------------------------------------------------

PYPROJECT = """\
    [project]
    name = "max-engine"
    version = "0.1.0"
    dependencies = [
        "fastapi>=0.111.0",
        "httpx>=0.27.0",
        "pydantic>=2.7.0",
        "uvicorn>=0.29.0",
    ]

    [project.optional-dependencies]
    dev = [
        "pytest>=8.0.0",
        "ruff>=0.4.0",
    ]
"""


def test_parse_python_direct_deps(tmp_path: Path):
    p = write(tmp_path, "pyproject.toml", PYPROJECT)
    pkgs = _parse_python(p)
    names = {pkg.name for pkg in pkgs}
    assert "fastapi" in names
    assert "httpx" in names
    assert all(pkg.ecosystem == "PyPI" for pkg in pkgs)
    assert all(pkg.version for pkg in pkgs)


def test_parse_python_optional_deps(tmp_path: Path):
    p = write(tmp_path, "pyproject.toml", PYPROJECT)
    pkgs = _parse_python(p)
    names = {pkg.name for pkg in pkgs}
    assert "pytest" in names


def test_parse_python_missing_file(tmp_path: Path):
    pkgs = _parse_python(tmp_path / "nonexistent.toml")
    assert pkgs == []


def test_parse_python_normalises_name(tmp_path: Path):
    p = write(tmp_path, "pyproject.toml", """\
        [project]
        dependencies = ["My_Package>=1.0.0"]
    """)
    pkgs = _parse_python(p)
    assert pkgs[0].name == "my-package"


# ---------------------------------------------------------------------------
# npm manifest parser
# ---------------------------------------------------------------------------

PACKAGE_LOCK_V3 = {
    "name": "app",
    "lockfileVersion": 3,
    "packages": {
        "node_modules/react": {"version": "18.2.0"},
        "node_modules/typescript": {"version": "5.4.5"},
        "node_modules/dev-tool": {"version": "1.0.0", "dev": True},
        "": {},  # root package entry — should be skipped
    },
}


def test_parse_npm_v3(tmp_path: Path):
    p = write(tmp_path, "package-lock.json", json.dumps(PACKAGE_LOCK_V3))
    pkgs = _parse_npm(p)
    names = {pkg.name for pkg in pkgs}
    assert "react" in names
    assert "typescript" in names
    # dev deps should be excluded
    assert "dev-tool" not in names
    assert all(pkg.ecosystem == "npm" for pkg in pkgs)
    assert all(pkg.version for pkg in pkgs)


def test_parse_npm_missing_file(tmp_path: Path):
    pkgs = _parse_npm(tmp_path / "nonexistent.json")
    assert pkgs == []


def test_parse_npm_invalid_json(tmp_path: Path):
    p = write(tmp_path, "package-lock.json", "not json {{{")
    pkgs = _parse_npm(p)
    assert pkgs == []


# ---------------------------------------------------------------------------
# Cargo.lock parser
# ---------------------------------------------------------------------------

CARGO_LOCK = """\
    # This file is automatically @generated by Cargo.
    [[package]]
    name = "tauri"
    version = "1.7.2"
    source = "registry+https://github.com/rust-lang/crates.io-index"

    [[package]]
    name = "serde"
    version = "1.0.203"
    source = "registry+https://github.com/rust-lang/crates.io-index"
"""


def test_parse_cargo(tmp_path: Path):
    p = write(tmp_path, "Cargo.lock", CARGO_LOCK)
    pkgs = _parse_cargo(p)
    names = {pkg.name for pkg in pkgs}
    assert "tauri" in names
    assert "serde" in names
    assert all(pkg.ecosystem == "crates.io" for pkg in pkgs)
    assert all(pkg.version for pkg in pkgs)


def test_parse_cargo_missing_file(tmp_path: Path):
    pkgs = _parse_cargo(tmp_path / "Cargo.lock")
    assert pkgs == []


# ---------------------------------------------------------------------------
# OSV severity extraction
# ---------------------------------------------------------------------------

def test_extract_severity_db_specific():
    vuln = {"database_specific": {"severity": "HIGH"}}
    assert _extract_severity(vuln) == "High"

def test_extract_severity_critical():
    vuln = {"database_specific": {"severity": "CRITICAL"}}
    assert _extract_severity(vuln) == "Critical"

def test_extract_severity_moderate():
    vuln = {"database_specific": {"severity": "MODERATE"}}
    assert _extract_severity(vuln) == "Medium"

def test_extract_fixed_version():
    vuln = {
        "affected": [{
            "package": {"name": "requests", "ecosystem": "PyPI"},
            "ranges": [{"type": "ECOSYSTEM", "events": [
                {"introduced": "0"}, {"fixed": "2.32.0"}
            ]}]
        }]
    }
    assert _extract_fixed_version(vuln, "requests") == "2.32.0"

def test_extract_fixed_version_missing():
    vuln = {"affected": []}
    assert _extract_fixed_version(vuln, "requests") == ""


# ---------------------------------------------------------------------------
# OSV query — mocked httpx client
# ---------------------------------------------------------------------------

OSV_BATCH_RESPONSE = {
    "results": [
        {
            "vulns": [{
                "id": "GHSA-test-1234",
                "aliases": ["CVE-2024-1234"],
                "summary": "Test vulnerability in requests",
                "details": "A test vulnerability.",
                "database_specific": {"severity": "HIGH"},
                "affected": [{
                    "package": {"name": "requests", "ecosystem": "PyPI"},
                    "ranges": [{"type": "ECOSYSTEM", "events": [
                        {"introduced": "0"}, {"fixed": "2.32.0"}
                    ]}]
                }]
            }]
        },
        {"vulns": []},  # no vulns for second package
    ]
}


def test_query_osv_returns_findings():
    packages = [
        Package("PyPI", "requests", "2.28.0"),
        Package("PyPI", "httpx", "0.27.0"),
    ]
    mock_resp = MagicMock()
    mock_resp.status_code = 200
    mock_resp.json.return_value = OSV_BATCH_RESPONSE

    mock_client = AsyncMock()
    mock_client.post = AsyncMock(return_value=mock_resp)
    mock_client.aclose = AsyncMock()

    findings = asyncio.run(query_osv(packages, client=mock_client))
    assert len(findings) == 1
    f = findings[0]
    assert f["cve_id"] == "CVE-2024-1234"
    assert f["package"] == "requests"
    assert f["installed_version"] == "2.28.0"
    assert f["fixed_version"] == "2.32.0"
    assert f["severity"] == "High"
    assert f["category"] == "sca"


def test_query_osv_empty_packages():
    findings = asyncio.run(query_osv([]))
    assert findings == []


def test_query_osv_network_error_returns_empty():
    mock_client = AsyncMock()
    mock_client.post = AsyncMock(side_effect=ConnectionError("timeout"))
    mock_client.aclose = AsyncMock()

    findings = asyncio.run(
        query_osv([Package("PyPI", "requests", "2.28.0")], client=mock_client)
    )
    assert findings == []


def test_query_osv_http_error_returns_empty():
    mock_resp = MagicMock()
    mock_resp.status_code = 500

    mock_client = AsyncMock()
    mock_client.post = AsyncMock(return_value=mock_resp)
    mock_client.aclose = AsyncMock()

    findings = asyncio.run(
        query_osv([Package("PyPI", "requests", "2.28.0")], client=mock_client)
    )
    assert findings == []


def test_query_osv_prefers_cve_id():
    """CVE alias should be preferred over GHSA in cve_id field."""
    packages = [Package("PyPI", "requests", "2.28.0")]
    mock_resp = MagicMock()
    mock_resp.status_code = 200
    mock_resp.json.return_value = {
        "results": [{"vulns": [{
            "id": "GHSA-xxxx-yyyy",
            "aliases": ["CVE-2024-9999"],
            "summary": "Test",
            "database_specific": {"severity": "CRITICAL"},
            "affected": [],
        }]}]
    }
    mock_client = AsyncMock()
    mock_client.post = AsyncMock(return_value=mock_resp)
    mock_client.aclose = AsyncMock()

    findings = asyncio.run(query_osv(packages, client=mock_client))
    assert findings[0]["cve_id"] == "CVE-2024-9999"
    assert findings[0]["severity"] == "Critical"


# ---------------------------------------------------------------------------
# parse_all integration (uses temp repo structure)
# ---------------------------------------------------------------------------

def test_parse_all_combines_sources(tmp_path: Path):
    write(tmp_path, "engine/pyproject.toml", PYPROJECT)
    write(tmp_path, "app/package-lock.json", json.dumps(PACKAGE_LOCK_V3))
    write(tmp_path, "app/src-tauri/Cargo.lock", CARGO_LOCK)

    pkgs = parse_all(str(tmp_path))
    ecosystems = {p.ecosystem for p in pkgs}
    assert "PyPI" in ecosystems
    assert "npm" in ecosystems
    assert "crates.io" in ecosystems


def test_parse_all_no_files(tmp_path: Path):
    pkgs = parse_all(str(tmp_path))
    assert pkgs == []
